from django.urls import path
from . import views
urlpatterns=[
    path('smms/',views.smms,name='smms'),
    path('insert/',views.insert,name='insert'),
    path('batch_insert/',views.batch_insert,name='batch_insert'),
    path('<id>/batch_update/',views.batch_update,name='batch_update'),
    path('home_view/',views.home_view,name='home_view'),
    path('display_batch/',views.display_batch,name='display_batch'),
    path('displaybatchinput/',views.displaybatchinput,name='displaybatchinput'),
    path('process_batch_entry/',views.process_batch_entry,name='process_batch_entry'),    
    path('b_delete/<pk>',views.b_delete,name='b_delete'),
    path('batch_delete/',views.batch_delete,name='batch_delete'),
    path('search1/', views.search_view_batch, name='search1'),
    path('edit/<int:id>/', views.edit_batch, name='edit_batch'),
    path('batch/<int:id>/', views.batch_detail, name='batch_detail'),
    path('batch_all_details/',views.batch_all_details,name='batch_all_details'),

    path('student_insert/',views.student_insert,name='student_insert'),
    path('<id>/student_update/',views.student_update,name='student_update'),
    path('display_student/',views.display_student,name='display_student'),
    path('process_student_entry/',views.process_student_entry,name='process_student_entry'),
    path('displaystudentinput/',views.displaystudentinput,name='displaystudentinput'),
    path('<id>/student_delete/',views.student_delete,name='student_delete'),

    path('course_insert/',views.course_insert,name='course_insert'),
    path('<id>/course_update/',views.course_update,name='course_update'),
    path('display_course/',views.display_course,name='display_course'),
    path('process_course_entry/',views.process_course_entry,name='process_course_entry'),
    path('displaycourseinput/',views.displaycourseinput,name='displaycourseinput'),
    path('c_delete/<pk>',views.c_delete,name='c_delete'),
    path('course_delete/',views.course_delete,name='course_delete'),
    path('search2/', views.search_view_course, name='search2'),
    path('edit1/<int:id>/', views.edit_course, name='edit_course'),
    path('course/<int:id>/', views.course_detail, name='course_detail'),
    path('course_all_details/',views.course_all_details,name='course_all_details'),

    path('sem_insert/',views.sem_insert,name='sem_insert'),
    path('<id>/sem_update/',views.sem_update,name='sem_update'),
    path('display_sem/',views.display_sem,name='display_sem'),
    path('process_sem_entry/',views.process_sem_entry,name='process_sem_entry'),
    path('displayseminput/',views.displayseminput,name='displayseminput'),
    path('s_delete/<pk>',views.s_delete,name='s_delete'),
    path('sem_delete/',views.sem_delete,name='sem_delete'),
    path('search3/', views.search_view_sem, name='search3'),
    path('edit2/<int:id>/', views.edit_sem, name='edit_sem'),
    path('sem/<int:id>/', views.sem_detail, name='sem_detail'),
    path('sem_all_details/',views.sem_all_details,name='sem_all_details'),

    path('exam_insert/',views.exam_insert,name='exam_insert'),
    path('<id>/exam_update/',views.exam_update,name='exam_update'),
    path('display_exam/',views.display_exam,name='display_exam'),
    path('process_exam_entry/',views.process_exam_entry,name='process_exam_entry'),
    path('displayexaminput/',views.displayexaminput,name='displayexaminput'),
    path('e_delete/<pk>',views.e_delete,name='e_delete'),
    path('exam_delete/',views.exam_delete,name='exam_delete'),
    path('search4/', views.search_view_exam, name='search4'),
    path('edit3/<int:id>/', views.edit_exam, name='edit_exam'),
    path('exam/<int:id>/', views.exam_detail, name='exam_detail'),
    path('exam_all_details/',views.exam_all_details,name='exam_all_details'),


    path('paper_insert/',views.paper_insert,name='paper_insert'),
    path('<id>/paper_update/',views.paper_update,name='paper_update'),
    path('display_paper/',views.display_paper,name='display_paper'),
    path('process_paper_entry/',views.process_paper_entry,name='process_paper_entry'),
    path('displaypaperinput/',views.displaypaperinput,name='displaypaperinput'),
    path('p_delete/<pk>',views.p_delete,name='p_delete'),
    path('paper_delete/',views.paper_delete,name='paper_delete'),
    path('search5/', views.search_view_paper, name='search5'),
    path('edit4/<int:id>/', views.edit_paper, name='edit_paper'),
    path('paper/<int:id>/', views.paper_detail, name='paper_detail'),
    path('paper_all_details/',views.paper_all_details,name='paper_all_details'),



    path('transaction_insert/',views.transaction_insert,name='transaction_insert'),
    path('<id>/transaction_update/',views.transaction_update,name='transaction_update'),
    path('display_transaction/',views.display_transaction,name='display_transaction'),
    path('process_transaction_entry/',views.process_transaction_entry,name='process_transaction_entry'),
    path('displaytransactioninput/',views.displaytransactioninput,name='displaytransactioninput'),
    path('<id>/transaction_delete/',views.transaction_delete,name='transaction_delete'),


    path('insert_employee/',views.insert_employee,name='insert_employee'),
    path('view_employee/',views.view_employee,name='view_employee'),
    path('update_view_employee1/',views.update_view_employee1,name='update_view_employee1'),
    path('delete_view_employee2/',views.delete_view_employee2,name='delete_view_employee2'),
    path('delete_employee/<int:pk>',views.delete_employee,name='delete_employee'),
    path('update_employee/<int:pk>',views.update_employee,name='update_employee'),
    path('search_employee/', views.search_employee, name='search_employee'),
    path('search_employee/', views.search_employee, name='search_employee'),
]

