# Generated by Django 5.0.7 on 2024-07-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchid', models.IntegerField(default=0)),
                ('batchno', models.CharField(max_length=10)),
            ],
        ),
    ]
