# Generated by Django 5.0.7 on 2024-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_batchmastermodel_batchid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchMasterModel',
            new_name='BatchMaster',
        ),
    ]
