# Generated by Django 5.0.7 on 2024-07-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_batchmastermodel_batchmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=60)),
                ('paper_code', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('batch_no', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.batchmaster')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.coursemaster')),
                ('exam_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.exammaster')),
                ('paper_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.papermaster')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.semmaster')),
            ],
        ),
    ]
