# Generated by Django 5.0.7 on 2024-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student_reg_no',
            field=models.CharField(max_length=10),
        ),
    ]
