# Generated by Django 5.0.7 on 2024-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_transaction_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paper_code',
            field=models.CharField(max_length=10),
        ),
    ]
