# Generated by Django 5.0.7 on 2024-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_transaction_paper_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student_reg_no',
            field=models.IntegerField(default=0),
        ),
    ]
