# Generated by Django 5.0.7 on 2024-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_transaction_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paper_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='student_reg_no',
        ),
    ]
