# Generated by Django 5.0.6 on 2024-07-14 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_batchmaster_batchid_alter_batchmaster_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='batchno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.batchmaster'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.coursemaster'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.semmaster'),
        ),
    ]
