# Generated by Django 5.0.6 on 2024-07-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_studentmaster_batchno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmaster',
            name='batchno',
        ),
    ]
