# Generated by Django 5.0.6 on 2024-07-14 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_studentmaster_batchno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='batchno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.batchmaster'),
        ),
    ]
