# Generated by Django 5.0.6 on 2024-07-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_studentmaster_batchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.coursemaster'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.semmaster'),
        ),
    ]
